type: yolo11
name: boat-detection-yolo11n
display_name: YOLO11n Boat Detection
model_path: best.onnx
input_width: 1280
input_height: 1280
stride: 32
nc: 8
classes:
  - boat-rgb
  - human head
  - human torso
  - outboard motor-rgb
  - boat
  - human
  - outboard motor
  - human-rgb
